### ISSUE TITLE
As a case worker or parent, I would like to know what the Star Rating means.

### ISSUE THREAD

**Issue by lutech** [FEISystems/ms-macwis-prototype#29] opened 2016-10-03 18:50 UTC
Definitions of the star rating must be added to each star rating and displayed for the User in the Search Fields and the Search Results table.

**Comment by ClaireReinken** [comment] 2016-10-06 14:58
Duplicate of Issue #47

**Closed as completed by ClaireReinken** 2016-10-06 14:58 UTC
Labels: duplicate, enhancement, 3 - Review

**Comment by lutech** [comment] 2016-10-07 04:01
This has been completed by other team member.
